#
# 这个文档包含了本博客的设定信息，你可以编辑它来个性化自己的博客，
#

# 你的博客名称，请用你想要的博客名替换“LOFFER”，以下修改都可类似处理
# 注意，“name: LOFFER”，冒号后面的空格不可以省略。
# 井号后面的文字是说明文档，不会被程序读取。

# 描述/签名
name: Jianqiao 'Cambridge' Mo 莫剑桥
name_eng: Jianqiao 'Cambridge' Mo
description:
affiliation: <a href="https://engineering.nyu.edu/student/jianqiao-cambridge-mo"><svg width="191" height="35" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd"> <g>  <title>Layer 1</title>  <g stroke-width="0" id="svg_1" transform="matrix(1.39089 0 0 1.45086 9.83723 60.6112)">   <path id="svg_2" fill-rule="nonzero" fill="#fff" d="m-3.22968,-38.96402l18.4,0l0,18.6l-18.4,0l0,-18.6z"></path>   <path id="svg_3" stroke="#231f20" fill="none" d="m-3.22968,-38.96402l18.4,0l0,18.6l-18.4,0l0,-18.6z"></path>   <path id="svg_4" fill-rule="nonzero" fill="#57068c" d="m22.87032,-32.26402l1,0l2.5,3.2l0,-3.3l1.2,0l0,5.3l-1,0l-2.7,-3.3l0,3.3l-1,0l0,-5.3m6.7,0.1l4,0l0,1l-2.9,0l0,1l2.5,0l0,1l-2.5,0l0,1.2l2.9,0l0,1l-4,0l0,-5.3m5.3,0.1l1.3,0l1,3.5l1.2,-3.6l1,0l1.2,3.6l1.1,-3.6l1.2,0l-1.8,5.3l-1,0l-1.2,-3.4l-1.2,3.4l-1,0l-1.8,-5.2zm14,3.1l-2,-3.1l1.4,0l1.3,2.2l1.2,-2.2l1.4,0l-2,3.2l0,2l-1.3,0l0,-2m4,-0.6c0,-1.5 1.1,-2.7 2.7,-2.7s2.8,1.2 2.8,2.7s-1.2,2.7 -2.8,2.7s-2.7,-1.3 -2.7,-2.7m4.4,0c0,-1 -0.7,-1.7 -1.6,-1.7c-1,0 -1.6,0.8 -1.6,1.7s0.7,1.6 1.6,1.6c1,0 1.6,-0.7 1.6,-1.6zm2.9,-2.6l2.4,0c0.7,0 1.2,0.1 1.5,0.5c0.3,0.3 0.5,0.7 0.5,1.2c0,0.8 -0.5,1.4 -1.2,1.6l1.3,1.9l-1.3,0l-1.2,-1.7l-0.9,0l0,1.7l-1.1,0l0,-5.3m2.3,2.6c0.6,0 0.9,-0.3 0.9,-0.7c0,-0.6 -0.4,-0.8 -1,-0.8l-1,0l0,1.5l1.1,0zm3.9,-2.5l1.1,0l0,2.2l2.1,-2.2l1.4,0l-2.1,2.2l2.2,3l-1.4,0l-1.6,-2.2l-0.6,0.6l0,1.6l-1.1,0l0,-5.3m9.1,3.1l0,-3l1.1,0l0,3c0,0.8 0.5,1.2 1.2,1.2s1.1,-0.4 1.1,-1.2l0,-3l1.2,0l0,3c0,1.5 -1,2.3 -2.3,2.3c-1.4,0 -2.3,-0.8 -2.3,-2.4m6.4,-2.9l1.2,0l2.4,3.2l0,-3.3l1.2,0l0,5.3l-1,0l-2.6,-3.3l0,3.3l-1.1,0l0,-5.3m6.7,0l1.2,0l0,5.2l-1.2,0l0,-5.2zm2.8,0.1l1.3,0l1.3,3.6l1.4,-3.7l1.2,0l-2,5.3l-1,0l-2.3,-5.2m6.9,0l4,0l0,1l-2.8,0l0,1l2.4,0l0,1l-2.4,0l0,1.2l2.8,0l0,1l-4,0l0,-5.3m5.8,0.1l2.4,0c0.6,0 1.2,0.1 1.5,0.5c0.3,0.3 0.5,0.7 0.5,1.2c0,0.8 -0.5,1.4 -1.2,1.6l1.3,1.9l-1.3,0l-1.2,-1.7l-0.9,0l0,1.7l-1.1,0l0,-5.3m2.3,2.6c0.6,0 0.9,-0.3 0.9,-0.7c0,-0.6 -0.4,-0.8 -1,-0.8l-1,0l0,1.5l1.1,0zm3.5,1.9l0.7,-0.8c0.4,0.4 1,0.6 1.5,0.6s0.8,-0.1 0.8,-0.4c0,-0.4 -0.2,-0.5 -1,-0.7c-1.1,-0.3 -1.8,-0.6 -1.8,-1.6s0.8,-1.6 1.8,-1.6c0.717,-0.046 1.427,0.167 2,0.6l-0.6,1c-0.5,-0.4 -1,-0.6 -1.4,-0.6s-0.7,0.2 -0.7,0.4c0,0.4 0.3,0.5 1.2,0.8c1,0.2 1.6,0.6 1.6,1.5c0,1 -0.8,1.7 -1.9,1.7c-0.8,0 -1.6,-0.3 -2.2,-0.9m6,-4.5l1.2,0l0,5.2l-1.2,0l0,-5.2zm4.4,1.1l-1.6,0l0,-1l4.3,0l0,1l-1.6,0l0,4.2l-1.1,0l0,-4.2zm5.9,2.1l-2,-3.2l1.3,0l1.2,2.2l1.3,-2.2l1.3,0l-2,3.2l0,2l-1.1,0l0,-2zm-109.2,11l-23.1,0l0,-23.1l23.1,0l0,23.1zm-15.1,-15.7c-1,1 -1.4,4.7 2.7,4.7c-2.4,-1.4 -2.1,-3.5 -1.1,-4.9c0,-0.2 -0.7,-1.9 -0.7,-1.6c0,0.7 -0.7,1.6 -0.9,1.8zm3.4,4.6c-1.6,-3 1.8,-5.1 1.8,-5.5c0,-1 -0.7,-3 -0.8,-2.8c-0.2,1 -1.5,2.3 -1.8,2.6c-2.4,2.7 -1.8,4.7 0.7,5.7l0.1,0zm0.4,0c0.2,-3.1 3.2,-3.5 3.4,-4c0.4,-1 -0.4,-3 -0.5,-2.9c-0.3,0.8 -0.9,1.5 -0.9,1.5c-2.5,1.8 -3,3.4 -2,5.3l0,0.1zm0.3,0c4.8,0.5 4.6,-5 4.6,-5c-0.3,0.6 -1,1 -1,1c-0.6,0.8 -3,1 -3.6,4zm-2.2,1.4l3.1,0l0,-1l-3.2,0l0,1l0.1,0zm1.3,6.7c0,0.2 0.4,0.3 0.5,0l0.8,-6.3l-2,0l0.7,6.3z"></path>  </g> </g></svg></a>  <br> <a href="https://cyber.nyu.edu/">CCS of Electrical and Computer Engineering</a> <br> 370 Jay St, Rm 1015 <br> Brooklyn, NY 11201

# 输入你的网站域名（如果你没有添加自己的域名，而是直接用GitHub pages分配的域名的话可以省略）
url:

# 添加你的博客的二级域名，一般来说是你的repository名
# 如果你的博客的URL是：(http://yourusername.github.io/repository-name)
# 那么就写成 "/repository-name"
baseurl: /


#
# 下面的设定都是可选的
#

# 你的博客logo图片URL，建议尺寸不超过300px × 300px
avatar: https://s2.loli.net/2022/03/14/WLxJtVm4YcCgvEq.png

# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: #https://raw.githubusercontent.com/FromEndWorld/LOFFER/master/images/favicon.png


# 菜单中的按钮
navigation:
  - name: Home
    url: /
  - name: About Me
    url: /aboutme
  - name: Research
    url: /tags
  - name: Recent Activities
    url: /activities
#  - name: Works
#    url: /works

# 每页的文章数
paginate: 10

# 文章简介的区分标记
excerpt_separator: <!-- more -->

# 你的社交网络链接，它们会作为图标出现在你的网站页脚中，可选填写
footer-links: 
  weibo:  #请输入你的微博个性域名 https://www.weibo.com/<thispart>
  behance: # https://www.behance.net/<>
  dribbble: # https://dribbble.com/<>
  email: jqmo.top/aboutme/#:~:text=Email%3A-,jqmo%40nyu%2Cedu,-Welcome%20to%20Jianqiao
  facebook: #https://www.facebook.com/<>
  flickr: #https://www.flickr.com/<>
  github: jianqiaomo
  instagram: #https://instagram.com/<>
  linkedin: jianqiao-cambridge-mo #https://www.linkedin.com/in/<>
  pinterest: #https://www.pinterest.com/<>
  rss: #随便填点啥RSS就能用了
  stackoverflow: # http://stackoverflow.com/<>
  tumblr: # https://<username>.tumblr.com
  twitter: # https://www.twitter.com/<your_twitter_username>
  googlescholar: rydgKnMAAAAJ # https://scholar.google.com/citations?user=<scholarID>
  youtube: # channel/<your_long_string> or user/<user-name>

# 站点页脚的文字
footer-text: Copyright (c) 2020 莫剑桥 Jianqiao Mo - All Rights Reserved.

#
# 评论，注意，请不要同时添加多种不同的评论区
#

# 输入Disqus shortname，即可添加评论区，请查阅文档，设置自己的disqus站点，不要继续使用我的站点loffer
disqus: #shortname

# 输入Gitalk相关设定，即可添加评论区，具体请看教程
gitalk:
  clientID: 91e699d173d31cf5c80b
  clientSecret: baa63c3140a1f724fb369581eaecb1c74f52253d
  repo: mywebpage
  owner: jianqiaomo

# 输入Google Analytics web tracking code
google_analytics:


#
# !! 以下所有设置都不需要更改 !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

