#
# 这个文档包含了本博客的设定信息，你可以编辑它来个性化自己的博客，
#

# 你的博客名称，请用你想要的博客名替换“LOFFER”，以下修改都可类似处理
# 注意，“name: LOFFER”，冒号后面的空格不可以省略。
# 井号后面的文字是说明文档，不会被程序读取。

# 描述/签名
name: Jianqiao 'Cambridge' Mo
description: Jianqiao Mo - Webpage
affiliation: <a href="https://cyber.nyu.edu/">CCS of Electrical and Computer Engineering</a> <br> <svg xmlns="http://www.w3.org/2000/svg" height="24" width="36" version="1" viewBox="-20.31 -5.775 176.02 34.65"><path d="M2.9 2.3h18.4v18.6H2.9z" fill="#FFF"/><path d="M2.9 2.3h18.4v18.6H2.9z" stroke="#231F20" fill="none"/><path d="M29 9h1l2.5 3.2V8.9h1.2v5.3h-1L30 10.9v3.3h-1V8.9m6.7.1h4v1h-2.9v1h2.5v1h-2.5v1.2h2.9v1h-4V8.9M41 9h1.3l1 3.5 1.2-3.6h1l1.2 3.6 1.1-3.6H49l-1.8 5.3h-1L45 10.8l-1.2 3.4h-1L41 9m14 3.1L53 9h1.4l1.3 2.2L56.9 9h1.4l-2 3.2v2H55v-2m4-.6c0-1.5 1.1-2.7 2.7-2.7s2.8 1.2 2.8 2.7c0 1.5-1.2 2.7-2.8 2.7-1.6 0-2.7-1.3-2.7-2.7m4.4 0c0-1-.7-1.7-1.6-1.7-1 0-1.6.8-1.6 1.7 0 .9.7 1.6 1.6 1.6 1 0 1.6-.7 1.6-1.6zM66.3 9h2.4c.7 0 1.2.1 1.5.5.3.3.5.7.5 1.2 0 .8-.5 1.4-1.2 1.6l1.3 1.9h-1.3l-1.2-1.7h-.9v1.7h-1.1V8.9m2.3 2.6c.6 0 .9-.3.9-.7 0-.6-.4-.8-1-.8h-1v1.5zM72.5 9h1.1v2.2L75.7 9h1.4L75 11.2l2.2 3h-1.4L74.2 12l-.6.6v1.6h-1.1V8.9m9.1 3.1V9h1.1v3c0 .8.5 1.2 1.2 1.2S85 12.8 85 12V9h1.2v3c0 1.5-1 2.3-2.3 2.3-1.4 0-2.3-.8-2.3-2.4M88 9h1.2l2.4 3.2V8.9h1.2v5.3h-1l-2.6-3.3v3.3h-1.1V8.9m6.7 0H96v5.2h-1.2zm2.8.1h1.3l1.3 3.6 1.4-3.7h1.2l-2 5.3h-1L97.5 9m6.9 0h4v1h-2.8v1h2.4v1h-2.4v1.2h2.8v1h-4V8.9m5.8.1h2.4c.6 0 1.2.1 1.5.5.3.3.5.7.5 1.2 0 .8-.5 1.4-1.2 1.6l1.3 1.9h-1.3l-1.2-1.7h-.9v1.7h-1.1V8.9m2.3 2.6c.6 0 .9-.3.9-.7 0-.6-.4-.8-1-.8h-1v1.5zm3.5 1.9l.7-.8c.4.4 1 .6 1.5.6s.8-.1.8-.4c0-.4-.2-.5-1-.7-1.1-.3-1.8-.6-1.8-1.6s.8-1.6 1.8-1.6a3 3 0 012 .6l-.6 1c-.5-.4-1-.6-1.4-.6-.4 0-.7.2-.7.4 0 .4.3.5 1.2.8 1 .2 1.6.6 1.6 1.5 0 1-.8 1.7-1.9 1.7-.8 0-1.6-.3-2.2-.9m6-4.5h1.2v5.2H122zm4.4 1.1h-1.6V9h4.3v1h-1.6v4.2h-1.1V10m5.9 2.1l-2-3.2h1.3l1.2 2.2 1.3-2.2h1.3l-2 3.2v2h-1.1v-2m-109.2 11H0V0h23.1zM8 7.4c-1 1-1.4 4.7 2.7 4.7-2.4-1.4-2.1-3.5-1.1-4.9 0-.2-.7-1.9-.7-1.6 0 .7-.7 1.6-.9 1.8zm3.4 4.6c-1.6-3 1.8-5.1 1.8-5.5 0-1-.7-3-.8-2.8-.2 1-1.5 2.3-1.8 2.6C8.2 9 8.8 11 11.3 12zm.4 0c.2-3.1 3.2-3.5 3.4-4 .4-1-.4-3-.5-2.9-.3.8-.9 1.5-.9 1.5-2.5 1.8-3 3.4-2 5.3zm.3 0c4.8.5 4.6-5 4.6-5-.3.6-1 1-1 1-.6.8-3 1-3.6 4zm-2.2 1.4H13v-1H9.8v1zm1.3 6.7c0 .2.4.3.5 0l.8-6.3h-2z" fill="#57068C"/></svg> <br> 370 Jay St, Rm 1015 <br> Brooklyn, NY 11201

# 输入你的网站域名（如果你没有添加自己的域名，而是直接用GitHub pages分配的域名的话可以省略）
url:

# 添加你的博客的二级域名，一般来说是你的repository名
# 如果你的博客的URL是：(http://yourusername.github.io/repository-name)
# 那么就写成 "/repository-name"
baseurl: /


#
# 下面的设定都是可选的
#

# 你的博客logo图片URL，建议尺寸不超过300px × 300px
avatar: https://s2.loli.net/2022/03/14/WLxJtVm4YcCgvEq.png

# 你的favicon（出现在浏览器tab上）图片URL，建议使用较小(64px × 64px)的图片
favicon: #https://raw.githubusercontent.com/FromEndWorld/LOFFER/master/images/favicon.png


# 菜单中的按钮
navigation:
  - name: Home
    url: /
  - name: About Me
    url: /aboutme
  - name: Activities
    url: /activities
  - name: Works
    url: /works

# 每页的文章数
paginate: 10

# 文章简介的区分标记
excerpt_separator: <!-- more -->

# 你的社交网络链接，它们会作为图标出现在你的网站页脚中，可选填写
footer-links: 
  weibo:  #请输入你的微博个性域名 https://www.weibo.com/<thispart>
  behance: # https://www.behance.net/<>
  dribbble: # https://dribbble.com/<>
  email: jqmo@nyu.edu
  facebook: #https://www.facebook.com/<>
  flickr: #https://www.flickr.com/<>
  github: jianqiaomo
  instagram: #https://instagram.com/<>
  linkedin: jianqiao-cambridge-mo #https://www.linkedin.com/in/<>
  pinterest: #https://www.pinterest.com/<>
  rss: #随便填点啥RSS就能用了
  stackoverflow: # http://stackoverflow.com/<>
  tumblr: # https://<username>.tumblr.com
  twitter: # https://www.twitter.com/<your_twitter_username>
  googlescholar: rydgKnMAAAAJ # https://scholar.google.com/citations?user=<scholarID>
  youtube: # channel/<your_long_string> or user/<user-name>

# 站点页脚的文字
footer-text: Copyright (c) 2020 莫剑桥.   (↑) My Contact/Email

#
# 评论，注意，请不要同时添加多种不同的评论区
#

# 输入Disqus shortname，即可添加评论区，请查阅文档，设置自己的disqus站点，不要继续使用我的站点loffer
disqus: #shortname

# 输入Gitalk相关设定，即可添加评论区，具体请看教程
gitalk:
  clientID: 91e699d173d31cf5c80b
  clientSecret: baa63c3140a1f724fb369581eaecb1c74f52253d
  repo: mywebpage
  owner: jianqiaomo

# 输入Google Analytics web tracking code
google_analytics:


#
# !! 以下所有设置都不需要更改 !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

